# Name of the workflow
name: Build and Deploy React App to GitHub Pages

# This workflow runs on every push to the "main" branch
on:
  push:
    branches: [ "main" ]

# A single job that builds and deploys the app
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        # The PUBLIC_URL environment variable is crucial for routing on GitHub Pages
        run: PUBLIC_URL=/${{ github.event.repository.name }} npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
